package sistema.service;


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import sistema.modelos.Campeonato;
import sistema.modelos.Categoria;
import sistema.modelos.Time;
import sistema.modelos.Usuario;

public class FakeService {

	private ArrayList<Usuario> usuarios = new ArrayList<Usuario>();
	private ArrayList<Campeonato> campeonatos = new ArrayList<Campeonato>();
	private ArrayList<Time> times = new ArrayList<Time>();
	private ArrayList<Categoria> categorias = new ArrayList<Categoria>();
	private ArrayList<String> cidades = new ArrayList<String>();
	
	public void setUsuarios(ArrayList<Usuario> usuarios) {
		this.usuarios = usuarios;
	}
	public List <Usuario> getUsuarios()
	{	
		return usuarios;	
	}
	public void setCampeonatos(ArrayList<Campeonato> campeonatos) {
		this.campeonatos = campeonatos;
	}
	public List <Campeonato> getCampeonatos()
	{	
		return campeonatos;	
	}
	public void setTimes(ArrayList<Time> times) {
		this.times = times;
	}
	public List <Time> getTimes()
	{
		return times;	
	}
	public ArrayList<String> getCidades() {
		return cidades;
	}
	public void setCidades(ArrayList<String> cidades) {
		this.cidades = cidades;
	}
	
	public ArrayList<Categoria> getCategorias() {
		return categorias;
	}
	public void setCategorias(ArrayList<Categoria> categorias) {
		this.categorias = categorias;
	}
	@SuppressWarnings("deprecation")
	public FakeService(){
		
		Campeonato camp = new Campeonato();
		
		camp.setNome("Cruzeirão 2017");
		camp.setAno(2017);
		camp.setDataInicio(new Date(117,0,5));
		camp.setDataTermino(new Date(117,11,10));
		camp.setValorTaxa(10);
		camp.setMinJog(5);
		camp.setMaxJog(15);
		camp.setMinTimeCat(10);
		campeonatos.add(camp);
		
		camp = new Campeonato();
		camp.setNome("Cruzeirão 2016");
		camp.setAno(2016);
		camp.setDataInicio(new Date(116,0,5));
		camp.setDataTermino(new Date(116,11,10));
		camp.setValorTaxa(10);
		camp.setMinJog(5);
		camp.setMaxJog(15);
		camp.setMinTimeCat(10);
		campeonatos.add(camp);
		
		Categoria cat = new Categoria();
		cat.setNome("Teste1");
		cat.setAnoMin(2000);
		cat.setCampeonato(campeonatos.get(0));
		cat.setSexo('M');
		cat.setHabCadJog(true);
		cat.setHabCadTime(true);
		categorias.add(cat);
		campeonatos.get(0).addCategoria(cat);
		
		cat = new Categoria();
		cat.setNome("Teste2");
		cat.setAnoMin(1990);
		cat.setCampeonato(campeonatos.get(0));
		cat.setSexo('M');
		cat.setHabCadJog(true);
		cat.setHabCadTime(true);
		categorias.add(cat);
		campeonatos.get(0).addCategoria(cat);
		
		cat = new Categoria();
		cat.setNome("Teste3");
		cat.setAnoMin(1995);
		cat.setCampeonato(campeonatos.get(0));
		cat.setSexo('F');
		cat.setHabCadJog(true);
		cat.setHabCadTime(true);
		categorias.add(cat);
		campeonatos.get(0).addCategoria(cat);
		
		cat = new Categoria();
		cat.setNome("Teste4");
		cat.setAnoMin(1999);
		cat.setCampeonato(campeonatos.get(1));
		cat.setSexo('M');
		cat.setHabCadJog(true);
		cat.setHabCadTime(true);
		categorias.add(cat);
		campeonatos.get(1).addCategoria(cat);
		
		cat = new Categoria();
		cat.setNome("Teste5");
		cat.setAnoMin(1980);
		cat.setCampeonato(campeonatos.get(1));
		cat.setSexo('M');
		cat.setHabCadJog(true);
		cat.setHabCadTime(true);
		categorias.add(cat);
		campeonatos.get(1).addCategoria(cat);
		
		Time time = new Time();
		time.setNome("Corinthians");
		time.setCidade("São Paulo");
		//time.setLogo(ImageIO.read(getClass().getResource("../../resources/sistema/1_0/imagens/corinthianslogo.png")));
		times.add(time);
		
		
		time = new Time();
		time.setNome("Palmeiras");
		time.setCidade("São Paulo");
		//time.setLogo(ImageIO.read(getClass().getResource("../../resources/sistema/1_0/imagens/palmeiraslogo.png")));
		times.add(time);
		
		time = new Time();
		time.setNome("Santos");
		time.setCidade("São Paulo");
		//time.setLogo(ImageIO.read(getClass().getResourceAsStream("../../resources/sistema/1_0/imagens/santoslogo.png")));
		times.add(time);
		
		time = new Time();
		time.setNome("São Paulo");
		time.setCidade("São Paulo");
		//time.setLogo(ImageIO.read(getClass().getResourceAsStream("../../resources/sistema/1_0/imagens/sãopaulologo.png")));
		times.add(time);
		
		Usuario user = new Usuario();
		user.setNome("Igor Cunha Gomes");
	    user.setSenha("123");
	    user.setRg("552576011");
	    user.setCpf("55257601184");
	    user.setCref("99999-a/aa");
	    user.setEmail("igor@cunha.com");
	    user.setDataNasc(new Date(1932,1,5));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Samuel Goncalves Cunha");
	    user.setSenha("123");
	    user.setRg("951061638");
	    user.setCpf("95106163897");
	    user.setCref("99999-a/aa");
	    user.setEmail("samuel@goncalves.com");
	    user.setDataNasc(new Date(1990,5,9));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Douglas Dias Rocha");
	    user.setSenha("123");
	    user.setRg("469353231");
	    user.setCpf("46935323126");
	    user.setCref("99999-a/aa");
	    user.setEmail("douglas@dias.com");
	    user.setDataNasc(new Date(1991,6,10));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Kai Ferreira Rocha");
	    user.setSenha("123");
	    user.setRg("499713112");
	    user.setCpf("49971311216");
	    user.setCref("99999-a/aa");
	    user.setEmail("kai@ferreira.com");
	    user.setDataNasc(new Date(2000,11,29));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Renan Silva Rocha");
	    user.setSenha("123");
	    user.setRg("392771304");
	    user.setCpf("39277130407");
	    user.setCref("99999-a/aa");
	    user.setEmail("renan@silva.com");
	    user.setDataNasc(new Date(1951,02,07));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Murilo Goncalves Silva");
	    user.setSenha("123");
	    user.setRg("400216495");
	    user.setCpf("40021649502");
	    user.setCref("99999-a/aa");
	    user.setEmail("murilo@goncalves.com");
	    user.setDataNasc(new Date(1980,11,27));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Luiz Barbosa Melo");
	    user.setSenha("123");
	    user.setRg("644121475");
	    user.setCpf("64412147509");
	    user.setCref("99999-a/aa");
	    user.setEmail("luiz@barbosa.com");
	    user.setDataNasc(new Date(1998,03,15));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Luan Barros Silva");
	    user.setSenha("123");
	    user.setRg("448671721");
	    user.setCpf("44867172103");
	    user.setCref("99999-a/aa");
	    user.setEmail("luan@barros.com");
	    user.setDataNasc(new Date(1960,10,8));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Victor Ribeiro Rocha");
	    user.setSenha("123");
	    user.setRg("123221517");
	    user.setCpf("12322151718");
	    user.setCref("99999-a/aa");
	    user.setEmail("victor@ribeiro.com");
	    user.setDataNasc(new Date(1980,03,20));
		usuarios.add(user);
		
		user = new Usuario();
		user.setNome("Kauan Costa Fernandes");
	    user.setSenha("123");
	    user.setRg("302353950");
	    user.setCpf("30235395021");
	    user.setCref("99999-a/aa");
	    user.setEmail("kauan@costa.com");
	    user.setDataNasc(new Date(1982,8,16));
		usuarios.add(user);
		
		cidades.add("Adamantina");
		cidades.add("Adolfo");
		cidades.add("Aguaí");
		cidades.add("Águas da Prata");
		cidades.add("Águas de Lindóia");
		cidades.add("Águas de Santa Bárbara");
		cidades.add("Águas de São Pedro");
		cidades.add("Agudos");
		cidades.add("Alambari");
		cidades.add("Alfredo Marcondes");
		cidades.add("Altair");
		cidades.add("Altinópolis");
		cidades.add("Alto Alegre");
		cidades.add("Alumínio");
		cidades.add("Álvares Florence");
		cidades.add("Álvares Machado");
		cidades.add("Álvaro de Carvalho");
		cidades.add("Alvinlândia");
		cidades.add("Americana");
		cidades.add("Américo Brasiliense");
		cidades.add("Américo de Campos");
		cidades.add("Amparo");
		cidades.add("Analândia");
		cidades.add("Andradina");
		cidades.add("Angatuba");
		cidades.add("Anhembi");
		cidades.add("Anhumas");
		cidades.add("Aparecida");
		cidades.add("Aparecida d`Oeste");
		cidades.add("Apiaí");
		cidades.add("Araçariguama");
		cidades.add("Araçatuba");
		cidades.add("Araçoiaba da Serra");
		cidades.add("Aramina");
		cidades.add("Arandu");
		cidades.add("Arapeí");
		cidades.add("Araraquara");
		cidades.add("Araras");
		cidades.add("Arco-Íris");
		cidades.add("Arealva");
		cidades.add("Areias");
		cidades.add("Areiópolis");
		cidades.add("Ariranha");
		cidades.add("Artur Nogueira");
		cidades.add("Arujá");
		cidades.add("Aspásia");
		cidades.add("Assis");
		cidades.add("Atibaia");
		cidades.add("Auriflama");
		cidades.add("Avaí");
		cidades.add("Avanhandava");
		cidades.add("Avaré");
		cidades.add("Bady Bassitt");
		cidades.add("Balbinos");
		cidades.add("Bálsamo");
		cidades.add("Bananal");
		cidades.add("Barão de Antonina");
		cidades.add("Barbosa");
		cidades.add("Bariri");
		cidades.add("Barra Bonita");
		cidades.add("Barra do Chapéu");
		cidades.add("Barra do Turvo");
		cidades.add("Barretos");
		cidades.add("Barrinha");
		cidades.add("Barueri");
		cidades.add("Bastos");
		cidades.add("Batatais");
		cidades.add("Bauru");
		cidades.add("Bebedouro");
		cidades.add("Bento de Abreu");
		cidades.add("Bernardino de Campos");
		cidades.add("Bertioga");
		cidades.add("Bilac");
		cidades.add("Birigui");
		cidades.add("Biritiba-Mirim");
		cidades.add("Boa Esperança do Sul");
		cidades.add("Bocaina");
		cidades.add("Bofete");
		cidades.add("Boituva");
		cidades.add("Bom Jesus dos Perdões");
		cidades.add("Bom Sucesso de Itararé");
		cidades.add("Borá");
		cidades.add("Boracéia");
		cidades.add("Borborema");
		cidades.add("Borebi");
		cidades.add("Botucatu");
		cidades.add("Bragança Paulista");
		cidades.add("Braúna");
		cidades.add("Brejo Alegre");
		cidades.add("Brodowski");
		cidades.add("Brotas");
		cidades.add("Buri");
		cidades.add("Buritama");
		cidades.add("Buritizal");
		cidades.add("Cabrália Paulista");
		cidades.add("Cabreúva");
		cidades.add("Caçapava");
		cidades.add("Cachoeira Paulista");
		cidades.add("Caconde");
		cidades.add("Cafelândia");
		cidades.add("Caiabu");
		cidades.add("Caieiras");
		cidades.add("Caiuá");
		cidades.add("Cajamar");
		cidades.add("Cajati");
		cidades.add("Cajobi");
		cidades.add("Cajuru");
		cidades.add("Campina do Monte Alegre");
		cidades.add("Campinas");
		cidades.add("Campo Limpo Paulista");
		cidades.add("Campos do Jordão");
		cidades.add("Campos Novos Paulista");
		cidades.add("Cananéia");
		cidades.add("Canas");
		cidades.add("Cândido Mota");
		cidades.add("Cândido Rodrigues");
		cidades.add("Canitar");
		cidades.add("Capão Bonito");
		cidades.add("Capela do Alto");
		cidades.add("Capivari");
		cidades.add("Caraguatatuba");
		cidades.add("Carapicuíba");
		cidades.add("Cardoso");
		cidades.add("Casa Branca");
		cidades.add("Cássia dos Coqueiros");
		cidades.add("Castilho");
		cidades.add("Catanduva");
		cidades.add("Catiguá");
		cidades.add("Cedral");
		cidades.add("Cerqueira César");
		cidades.add("Cerquilho");
		cidades.add("Cesário Lange");
		cidades.add("Charqueada");
		cidades.add("Chavantes");
		cidades.add("Clementina");
		cidades.add("Colina");
		cidades.add("Colômbia");
		cidades.add("Conchal");
		cidades.add("Conchas");
		cidades.add("Cordeirópolis");
		cidades.add("Coroados");
		cidades.add("Coronel Macedo");
		cidades.add("Corumbataí");
		cidades.add("Cosmópolis");
		cidades.add("Cosmorama");
		cidades.add("Cotia");
		cidades.add("Cravinhos");
		cidades.add("Cristais Paulista");
		cidades.add("Cruzália");
		cidades.add("Cruzeiro");
		cidades.add("Cubatão");
		cidades.add("Cunha");
		cidades.add("Descalvado");
		cidades.add("Diadema");
		cidades.add("Dirce Reis");
		cidades.add("Divinolândia");
		cidades.add("Dobrada");
		cidades.add("Dois Córregos");
		cidades.add("Dolcinópolis");
		cidades.add("Dourado");
		cidades.add("Dracena");
		cidades.add("Duartina");
		cidades.add("Dumont");
		cidades.add("Echaporã");
		cidades.add("Eldorado");
		cidades.add("Elias Fausto");
		cidades.add("Elisiário");
		cidades.add("Embaúba");
		cidades.add("Embu das Artes");
		cidades.add("Embu-Guaçu");
		cidades.add("Emilianópolis");
		cidades.add("Engenheiro Coelho");
		cidades.add("Espírito Santo do Pinhal");
		cidades.add("Espírito Santo do Turvo");
		cidades.add("Estiva Gerbi");
		cidades.add("Estrela do Norte");
		cidades.add("Estrela d`Oeste");
		cidades.add("Euclides da Cunha Paulista");
		cidades.add("Fartura");
		cidades.add("Fernando Prestes");
		cidades.add("Fernandópolis");
		cidades.add("Fernão");
		cidades.add("Ferraz de Vasconcelos");
		cidades.add("Flora Rica");
		cidades.add("Floreal");
		cidades.add("Flórida Paulista");
		cidades.add("Florínia");
		cidades.add("Franca");
		cidades.add("Francisco Morato");
		cidades.add("Franco da Rocha");
		cidades.add("Gabriel Monteiro");
		cidades.add("Gália");
		cidades.add("Garça");
		cidades.add("Gastão Vidigal");
		cidades.add("Gavião Peixoto");
		cidades.add("General Salgado");
		cidades.add("Getulina");
		cidades.add("Glicério");
		cidades.add("Guaiçara");
		cidades.add("Guaimbê");
		cidades.add("Guaíra");
		cidades.add("Guapiaçu");
		cidades.add("Guapiara");
		cidades.add("Guará");
		cidades.add("Guaraçaí");
		cidades.add("Guaraci");
		cidades.add("Guarani d`Oeste");
		cidades.add("Guarantã");
		cidades.add("Guararapes");
		cidades.add("Guararema");
		cidades.add("Guaratinguetá");
		cidades.add("Guareí");
		cidades.add("Guariba");
		cidades.add("Guarujá");
		cidades.add("Guarulhos");
		cidades.add("Guatapará");
		cidades.add("Guzolândia");
		cidades.add("Herculândia");
		cidades.add("Holambra");
		cidades.add("Hortolândia");
		cidades.add("Iacanga");
		cidades.add("Iacri");
		cidades.add("Iaras");
		cidades.add("Ibaté");
		cidades.add("Ibirá");
		cidades.add("Ibirarema");
		cidades.add("Ibitinga");
		cidades.add("Ibiúna");
		cidades.add("Icém");
		cidades.add("Iepê");
		cidades.add("Igaraçu do Tietê");
		cidades.add("Igarapava");
		cidades.add("Igaratá");
		cidades.add("Iguape");
		cidades.add("Ilha Comprida");
		cidades.add("Ilha Solteira");
		cidades.add("Ilhabela");
		cidades.add("Indaiatuba");
		cidades.add("Indiana");
		cidades.add("Indiaporã");
		cidades.add("Inúbia Paulista");
		cidades.add("Ipaussu");
		cidades.add("Iperó");
		cidades.add("Ipeúna");
		cidades.add("Ipiguá");
		cidades.add("Iporanga");
		cidades.add("Ipuã");
		cidades.add("Iracemápolis");
		cidades.add("Irapuã");
		cidades.add("Irapuru");
		cidades.add("Itaberá");
		cidades.add("Itaí");
		cidades.add("Itajobi");
		cidades.add("Itaju");
		cidades.add("Itanhaém");
		cidades.add("Itaóca");
		cidades.add("Itapecerica da Serra");
		cidades.add("Itapetininga");
		cidades.add("Itapeva");
		cidades.add("Itapevi");
		cidades.add("Itapira");
		cidades.add("Itapirapuã Paulista");
		cidades.add("Itápolis");
		cidades.add("Itaporanga");
		cidades.add("Itapuí");
		cidades.add("Itapura");
		cidades.add("Itaquaquecetuba");
		cidades.add("Itararé");
		cidades.add("Itariri");
		cidades.add("Itatiba");
		cidades.add("Itatinga");
		cidades.add("Itirapina");
		cidades.add("Itirapuã");
		cidades.add("Itobi");
		cidades.add("Itu");
		cidades.add("Itupeva");
		cidades.add("Ituverava");
		cidades.add("Jaborandi");
		cidades.add("Jaboticabal");
		cidades.add("Jacareí");
		cidades.add("Jaci");
		cidades.add("Jacupiranga");
		cidades.add("Jaguariúna");
		cidades.add("Jales");
		cidades.add("Jambeiro");
		cidades.add("Jandira");
		cidades.add("Jardinópolis");
		cidades.add("Jarinu");
		cidades.add("Jaú");
		cidades.add("Jeriquara");
		cidades.add("Joanópolis");
		cidades.add("João Ramalho");
		cidades.add("José Bonifácio");
		cidades.add("Júlio Mesquita");
		cidades.add("Jumirim");
		cidades.add("Jundiaí");
		cidades.add("Junqueirópolis");
		cidades.add("Juquiá");
		cidades.add("Juquitiba");
		cidades.add("Lagoinha");
		cidades.add("Laranjal Paulista");
		cidades.add("Lavínia");
		cidades.add("Lavrinhas");
		cidades.add("Leme");
		cidades.add("Lençóis Paulista");
		cidades.add("Limeira");
		cidades.add("Lindóia");
		cidades.add("Lins");
		cidades.add("Lorena");
		cidades.add("Lourdes");
		cidades.add("Louveira");
		cidades.add("Lucélia");
		cidades.add("Lucianópolis");
		cidades.add("Luís Antônio");
		cidades.add("Luiziânia");
		cidades.add("Lupércio");
		cidades.add("Lutécia");
		cidades.add("Macatuba");
		cidades.add("Macaubal");
		cidades.add("Macedônia");
		cidades.add("Magda");
		cidades.add("Mairinque");
		cidades.add("Mairiporã");
		cidades.add("Manduri");
		cidades.add("Marabá Paulista");
		cidades.add("Maracaí");
		cidades.add("Marapoama");
		cidades.add("Mariápolis");
		cidades.add("Marília");
		cidades.add("Marinópolis");
		cidades.add("Martinópolis");
		cidades.add("Matão");
		cidades.add("Mauá");
		cidades.add("Mendonça");
		cidades.add("Meridiano");
		cidades.add("Mesópolis");
		cidades.add("Miguelópolis");
		cidades.add("Mineiros do Tietê");
		cidades.add("Mira Estrela");
		cidades.add("Miracatu");
		cidades.add("Mirandópolis");
		cidades.add("Mirante do Paranapanema");
		cidades.add("Mirassol");
		cidades.add("Mirassolândia");
		cidades.add("Mococa");
		cidades.add("Mogi das Cruzes");
		cidades.add("Mogi Guaçu");
		cidades.add("Mogi Mirim");
		cidades.add("Mombuca");
		cidades.add("Monções");
		cidades.add("Mongaguá");
		cidades.add("Monte Alegre do Sul");
		cidades.add("Monte Alto");
		cidades.add("Monte Aprazível");
		cidades.add("Monte Azul Paulista");
		cidades.add("Monte Castelo");
		cidades.add("Monte Mor");
		cidades.add("Monteiro Lobato");
		cidades.add("Morro Agudo");
		cidades.add("Morungaba");
		cidades.add("Motuca");
		cidades.add("Murutinga do Sul");
		cidades.add("Nantes");
		cidades.add("Narandiba");
		cidades.add("Natividade da Serra");
		cidades.add("Nazaré Paulista");
		cidades.add("Neves Paulista");
		cidades.add("Nhandeara");
		cidades.add("Nipoã");
		cidades.add("Nova Aliança");
		cidades.add("Nova Campina");
		cidades.add("Nova Canaã Paulista");
		cidades.add("Nova Castilho");
		cidades.add("Nova Europa");
		cidades.add("Nova Granada");
		cidades.add("Nova Guataporanga");
		cidades.add("Nova Independência");
		cidades.add("Nova Luzitânia");
		cidades.add("Nova Odessa");
		cidades.add("Novais");
		cidades.add("Novo Horizonte");
		cidades.add("Nuporanga");
		cidades.add("Ocauçu");
		cidades.add("Óleo");
		cidades.add("Olímpia");
		cidades.add("Onda Verde");
		cidades.add("Oriente");
		cidades.add("Orindiúva");
		cidades.add("Orlândia");
		cidades.add("Osasco");
		cidades.add("Oscar Bressane");
		cidades.add("Osvaldo Cruz");
		cidades.add("Ourinhos");
		cidades.add("Ouro Verde");
		cidades.add("Ouroeste");
		cidades.add("Pacaembu");
		cidades.add("Palestina");
		cidades.add("Palmares Paulista");
		cidades.add("Palmeira d`Oeste");
		cidades.add("Palmital");
		cidades.add("Panorama");
		cidades.add("Paraguaçu Paulista");
		cidades.add("Paraibuna");
		cidades.add("Paraíso");
		cidades.add("Paranapanema");
		cidades.add("Paranapuã");
		cidades.add("Parapuã");
		cidades.add("Pardinho");
		cidades.add("Pariquera-Açu");
		cidades.add("Parisi");
		cidades.add("Patrocínio Paulista");
		cidades.add("Paulicéia");
		cidades.add("Paulínia");
		cidades.add("Paulistânia");
		cidades.add("Paulo de Faria");
		cidades.add("Pederneiras");
		cidades.add("Pedra Bela");
		cidades.add("Pedranópolis");
		cidades.add("Pedregulho");
		cidades.add("Pedreira");
		cidades.add("Pedrinhas Paulista");
		cidades.add("Pedro de Toledo");
		cidades.add("Penápolis");
		cidades.add("Pereira Barreto");
		cidades.add("Pereiras");
		cidades.add("Peruíbe");
		cidades.add("Piacatu");
		cidades.add("Piedade");
		cidades.add("Pilar do Sul");
		cidades.add("Pindamonhangaba");
		cidades.add("Pindorama");
		cidades.add("Pinhalzinho");
		cidades.add("Piquerobi");
		cidades.add("Piquete");
		cidades.add("Piracaia");
		cidades.add("Piracicaba");
		cidades.add("Piraju");
		cidades.add("Pirajuí");
		cidades.add("Pirangi");
		cidades.add("Pirapora do Bom Jesus");
		cidades.add("Pirapozinho");
		cidades.add("Pirassununga");
		cidades.add("Piratininga");
		cidades.add("Pitangueiras");
		cidades.add("Planalto");
		cidades.add("Platina");
		cidades.add("Poá");
		cidades.add("Poloni");
		cidades.add("Pompéia");
		cidades.add("Pongaí");
		cidades.add("Pontal");
		cidades.add("Pontalinda");
		cidades.add("Pontes Gestal");
		cidades.add("Populina");
		cidades.add("Porangaba");
		cidades.add("Porto Feliz");
		cidades.add("Porto Ferreira");
		cidades.add("Potim");
		cidades.add("Potirendaba");
		cidades.add("Pracinha");
		cidades.add("Pradópolis");
		cidades.add("Praia Grande");
		cidades.add("Pratânia");
		cidades.add("Presidente Alves");
		cidades.add("Presidente Bernardes");
		cidades.add("Presidente Epitácio");
		cidades.add("Presidente Prudente");
		cidades.add("Presidente Venceslau");
		cidades.add("Promissão");
		cidades.add("Quadra");
		cidades.add("Quatá");
		cidades.add("Queiroz");
		cidades.add("Queluz");
		cidades.add("Quintana");
		cidades.add("Rafard");
		cidades.add("Rancharia");
		cidades.add("Redenção da Serra");
		cidades.add("Regente Feijó");
		cidades.add("Reginópolis");
		cidades.add("Registro");
		cidades.add("Restinga");
		cidades.add("Ribeira");
		cidades.add("Ribeirão Bonito");
		cidades.add("Ribeirão Branco");
		cidades.add("Ribeirão Corrente");
		cidades.add("Ribeirão do Sul");
		cidades.add("Ribeirão dos Índios");
		cidades.add("Ribeirão Grande");
		cidades.add("Ribeirão Pires");
		cidades.add("Ribeirão Preto");
		cidades.add("Rifaina");
		cidades.add("Rincão");
		cidades.add("Rinópolis");
		cidades.add("Rio Claro");
		cidades.add("Rio das Pedras");
		cidades.add("Rio Grande da Serra");
		cidades.add("Riolândia");
		cidades.add("Riversul");
		cidades.add("Rosana");
		cidades.add("Roseira");
		cidades.add("Rubiácea");
		cidades.add("Rubinéia");
		cidades.add("Sabino");
		cidades.add("Sagres");
		cidades.add("Sales");
		cidades.add("Sales Oliveira");
		cidades.add("Salesópolis");
		cidades.add("Salmourão");
		cidades.add("Saltinho");
		cidades.add("Salto");
		cidades.add("Salto de Pirapora");
		cidades.add("Salto Grande");
		cidades.add("Sandovalina");
		cidades.add("Santa Adélia");
		cidades.add("Santa Albertina");
		cidades.add("Santa Bárbara d`Oeste");
		cidades.add("Santa Branca");
		cidades.add("Santa Clara d`Oeste");
		cidades.add("Santa Cruz da Conceição");
		cidades.add("Santa Cruz da Esperança");
		cidades.add("Santa Cruz das Palmeiras");
		cidades.add("Santa Cruz do Rio Pardo");
		cidades.add("Santa Ernestina");
		cidades.add("Santa Fé do Sul");
		cidades.add("Santa Gertrudes");
		cidades.add("Santa Isabel");
		cidades.add("Santa Lúcia");
		cidades.add("Santa Maria da Serra");
		cidades.add("Santa Mercedes");
		cidades.add("Santa Rita do Passa Quatro");
		cidades.add("Santa Rita d`Oeste");
		cidades.add("Santa Rosa de Viterbo");
		cidades.add("Santa Salete");
		cidades.add("Santana da Ponte Pensa");
		cidades.add("Santana de Parnaíba");
		cidades.add("Santo Anastácio");
		cidades.add("Santo André");
		cidades.add("Santo Antônio da Alegria");
		cidades.add("Santo Antônio de Posse");
		cidades.add("Santo Antônio do Aracanguá");
		cidades.add("Santo Antônio do Jardim");
		cidades.add("Santo Antônio do Pinhal");
		cidades.add("Santo Expedito");
		cidades.add("Santópolis do Aguapeí");
		cidades.add("Santos");
		cidades.add("São Bento do Sapucaí");
		cidades.add("São Bernardo do Campo");
		cidades.add("São Caetano do Sul");
		cidades.add("São Carlos");
		cidades.add("São Francisco");
		cidades.add("São João da Boa Vista");
		cidades.add("São João das Duas Pontes");
		cidades.add("São João de Iracema");
		cidades.add("São João do Pau d`Alho");
		cidades.add("São Joaquim da Barra");
		cidades.add("São José da Bela Vista");
		cidades.add("São José do Barreiro");
		cidades.add("São José do Rio Pardo");
		cidades.add("São José do Rio Preto");
		cidades.add("São José dos Campos");
		cidades.add("São Lourenço da Serra");
		cidades.add("São Luís do Paraitinga");
		cidades.add("São Manuel");
		cidades.add("São Miguel Arcanjo");
		cidades.add("São Paulo");
		cidades.add("São Pedro");
		cidades.add("São Pedro do Turvo");
		cidades.add("São Roque");
		cidades.add("São Sebastião");
		cidades.add("São Sebastião da Grama");
		cidades.add("São Simão");
		cidades.add("São Vicente");
		cidades.add("Sarapuí");
		cidades.add("Sarutaiá");
		cidades.add("Sebastianópolis do Sul");
		cidades.add("Serra Azul");
		cidades.add("Serra Negra");
		cidades.add("Serrana");
		cidades.add("Sertãozinho");
		cidades.add("Sete Barras");
		cidades.add("Severínia");
		cidades.add("Silveiras");
		cidades.add("Socorro");
		cidades.add("Sorocaba");
		cidades.add("Sud Mennucci");
		cidades.add("Sumaré");
		cidades.add("Suzanápolis");
		cidades.add("Suzano");
		cidades.add("Tabapuã");
		cidades.add("Tabatinga");
		cidades.add("Taboão da Serra");
		cidades.add("Taciba");
		cidades.add("Taguaí");
		cidades.add("Taiaçu");
		cidades.add("Taiúva");
		cidades.add("Tambaú");
		cidades.add("Tanabi");
		cidades.add("Tapiraí");
		cidades.add("Tapiratiba");
		cidades.add("Taquaral");
		cidades.add("Taquaritinga");
		cidades.add("Taquarituba");
		cidades.add("Taquarivaí");
		cidades.add("Tarabai");
		cidades.add("Tarumã");
		cidades.add("Tatuí");
		cidades.add("Taubaté");
		cidades.add("Tejupá");
		cidades.add("Teodoro Sampaio");
		cidades.add("Terra Roxa");
		cidades.add("Tietê");
		cidades.add("Timburi");
		cidades.add("Torre de Pedra");
		cidades.add("Torrinha");
		cidades.add("Trabiju");
		cidades.add("Tremembé");
		cidades.add("Três Fronteiras");
		cidades.add("Tuiuti");
		cidades.add("Tupã");
		cidades.add("Tupi Paulista");
		cidades.add("Turiúba");
		cidades.add("Turmalina");
		cidades.add("Ubarana");
		cidades.add("Ubatuba");
		cidades.add("Ubirajara");
		cidades.add("Uchoa");
		cidades.add("União Paulista");
		cidades.add("Urânia");
		cidades.add("Uru");
		cidades.add("Urupês");
		cidades.add("Valentim Gentil");
		cidades.add("Valinhos");
		cidades.add("Valparaíso");
		cidades.add("Vargem");
		cidades.add("Vargem Grande do Sul");
		cidades.add("Vargem Grande Paulista");
		cidades.add("Várzea Paulista");
		cidades.add("Vera Cruz");
		cidades.add("Vinhedo");
		cidades.add("Viradouro");
		cidades.add("Vista Alegre do Alto");
		cidades.add("Vitória Brasil");
		cidades.add("Votorantim");
		cidades.add("Votuporanga");
		cidades.add("Zacarias");
	}
	
}
